version: "3.8"

services:
  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped

  node:
    image: node:21-alpine
    tty: true
    volumes:
      - ./:/var/www
    restart: unless-stopped

  build:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    entrypoint: ['php', '/var/www/build.php']